# Generated by Django 4.1.1 on 2022-10-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=150)),
                ('finch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bird_house', to='main_app.finch')),
            ],
        ),
    ]
